services :

    keycloak_user.user_provider:
        class: Nydareld\KeycloakUserBundle\Security\User\UserProvider
        arguments:
            $realm: keycloak_user.credentials.realm
            $url: keycloak_user.credentials.realm
            $clientId: keycloak_user.credentials.clientId
