services :

    nydareld_keycloak_user.user_provider:
        class: Nydareld\KeycloakUserBundle\Security\User\UserProvider
        arguments:
            $realm: ''
            $url: ''
            $clientId: ''

    nydareld_keycloak_user.authenticator:
        class: Nydareld\KeycloakUserBundle\Security\JWTAuthenticator
        arguments:
            $jwtDecoder: '@nydareld_keycloak_user.jwt_decoder'

    nydareld_keycloak_user.jwt_decoder:
        class: Nydareld\KeycloakUserBundle\Services\JWTDecoder
        arguments:
            $openidConfifgurationEndpoint: ''
            $cacheProvider: null
