services :

    nydareld_keycloak_user.user_provider:
        class: Nydareld\KeycloakUserBundle\Security\User\UserProvider
        arguments:
            $realm: ''
            $url: ''
            $clientId: ''

    nydareld_keycloak_user.authenticator:
        class: Nydareld\KeycloakUserBundle\Security\JWTAuthenticator
